# Generated by Django 3.1.1 on 2020-09-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
    ]
